(define the-empty-environment '())
(define (enclosing-environment env) (cdr env))
(define (first-frame env) (car env))
(define (frame-variables frame)(car frame))
(define (frame-values frame)(cdr frame))

;a

(define (lookup-variable-value var env)
    (define (env-loop env)
    (define (scan vars vals) 
    (cond ((null? vars)
       (env-loop (enclosing-environment env)))
        ((eq? var (car vars)) 
            (let ((found-val (car vals)))
                (if (eq? found-val '*unassigned*)
                    (error "Unassigned internal definition" found-val)
                    found-val)))
        (else (scan (cdr vars) (cdr vals)))))
    (if (eq? env the-empty-environment) 
        (error "Unbound variable" var) 
        (let ((frame (first-frame env)))
          (scan (frame-variables frame)
                (frame-values frame)))))
    (env-loop env))