(load "test-manager/load.scm")
(load "ch-3/ex-3-26.scm")


(define-each-test
(let ((table (make-table < )))
   (assert-false ((table 'lookup-proc) (list 2)) "should be an empty lookup table in the begining")
   )

(let ((table (make-table < )))
   ((table 'insert-proc!) (list 1) 'a) 
   (assert-false ((table 'lookup-proc) (list 2)) "should be an empty lookup table in the begining")
   (check (equal? 'a ((table 'lookup-proc)(list 1))) "should find the expected value in a one dimensional lookup table")
   )

(let ((table (make-table < )))
   ((table 'insert-proc!) (list 1) 'a) 
   ((table 'insert-proc!) (list 2) 'b) 
   ((table 'insert-proc!) (list -1) 'c) 
   (check (equal? 'b ((table 'lookup-proc)(list 2))) "should be able to find the second element stored in the lookup table")
   (check (equal? 'c ((table 'lookup-proc)(list -1))) "should be able to find the third element stored in the lookup table")
   )

(let ((table (make-table < )))
   ((table 'insert-proc!) (list 1) 'a) 
   ((table 'insert-proc!) (list 2) 'b) 
   ((table 'insert-proc!) (list -1) 'c) 
   ((table 'insert-proc!) (list 4) 'd) 
   ((table 'insert-proc!) (list -2) 'e)
   ((table 'insert-proc!) (list 1) 'z)
   (check (equal? 'b ((table 'lookup-proc)(list 2))) "should find a stored element in a deep tree")
   (check (equal? 'c ((table 'lookup-proc)(list -1))) "should find a stored element in a deep tree")
   (check (equal? 'z ((table 'lookup-proc)(list 1))) "should be able to update the value of an existing record")
   )

(let ((table (make-table < )))
   ((table 'insert-proc!) (list 1 2) 'a) 
   (check (equal? (list (cons 2 'a) '() '()) ((table 'lookup-proc)(list 1))) "should find the expected value in an mutlti dimensional lookup table")
   (check (equal? 'a ((table 'lookup-proc)(list 1 2))) "should find the expected value in an mutlti dimensional lookup table")
   )

(let ((table (make-table < )))
   ((table 'insert-proc!) (list 1 2) 'a) 
   ((table 'insert-proc!) (list 2 1) 'c) 
   ((table 'insert-proc!) (list -1 1) 'b) 
   ((table 'insert-proc!) (list 1 2) 'z) 
   (check (equal? 'c ((table 'lookup-proc)(list 2 1))) "should be able to insert deep if the target node is not the root node")
   (check (equal? 'b ((table 'lookup-proc)(list -1 1))) "should be able to insert deep if the target node is not the root node")
   (check (equal? 'z ((table 'lookup-proc)(list 1 2))) "should be able to change an existing value in a multi dimensional lookup table")
   )

(let ((table (make-table < )))
   ((table 'insert-proc!) (list 1) 'a) 
   ((table 'insert-proc!) (list 1 2) 'a) 
   (check (equal? 'a ((table 'lookup-proc)(list 1 2))) "should be able to increase the dimension of the lookup table")
   )

(let ((table (make-table < )))
   ((table 'insert-proc!) (list 1 2) 'a) 
   ((table 'insert-proc!) (list 2 1) 'c) 
   ((table 'insert-proc!) (list -1 1) 'b) 
   ((table 'insert-proc!) (list 1) 'a) 
   ((table 'insert-proc!) (list 2 1) 'k) 
   ((table 'insert-proc!) (list -1 1) 'e) 
   ((table 'insert-proc!) (list 5 6 7 8 9) 'z) 
   (check (equal? 'k ((table 'lookup-proc)(list 2 1))) "shoud pass the acceptance test")
   (check (equal? 'e ((table 'lookup-proc)(list -1 1))) "shoud pass the acceptance test")
   (check (equal? 'a ((table 'lookup-proc)(list 1))) "shoud pass the acceptance test")
   (check (equal? 'z ((table 'lookup-proc)(list 5 6 7 8 9))) "shoud pass the acceptance test")
   (assert-false ((table 'lookup-proc)(list 5 6 7 8 9 11 23 34)) "shoud pass the acceptance test")
   (assert-false ((table 'lookup-proc)(list 5 6 55)) "shoud pass the acceptance test")
   )

)



(run-registered-tests)