;first part

(define yatch-owner-daughters-puzzle
    (let ((gabrielle-yatch-owner 'barnacle)
        (lorna-yatch-owner 'moore)
        (rosalind-yatch-owner 'hall)
        (melissa-yatch-owner 'downing)
        (mary-ann-father 'moore)
        (melissa-father 'barnacle)
        (mary-ann-yatch-owner (amb 'barnacle 'moore 'hall 'downing 'parker)))
            (require (not (eq? mary-ann-yatch-owner gabrielle-yatch-owner)))
            (require (not (eq? mary-ann-yatch-owner lorna-yatch-owner)))
            (require (not (eq? mary-ann-yatch-owner rosalind-yatch-owner)))
            (require (not (eq? mary-ann-yatch-owner melissa-yatch-owner)))
                (let ((gabrielle-father (amb 'barnacle 'moore 'hall 'downing 'parker))) 
                   (require (not (eq? melissa-father gabrielle-father))) 
                   (require (not (eq? gabrielle-yatch-owner gabrielle-father)))
                        (let ((rosalind-father (amb 'barnacle 'moore 'hall 'downing 'parker))) 
                            (require (not (eq? melissa-father rosalind-father))) 
                            (require (not (eq? gabrielle-father rosalind-father))) 
                            (require (not (eq? rosalind-yatch-owner rosalind-father))) 
                            )
                        (let ((lorna-father (amb 'barnacle 'moore 'hall 'downing 'parker)))
                            (require (not (= gabrielle-father lorna-father)))
                            (require (not (= melissa-father lorna-father)))
                            (require (not (= rosalind-father lorna-father)))
                                lorna-father))))
(display (yatch-owner-daughters-puzzle))
;second part

(define yatch-owner-daughters-puzzle
    (let ((gabrielle-yatch-owner 'barnacle)
        (lorna-yatch-owner 'moore)
        (rosalind-yatch-owner 'hall)
        (melissa-yatch-owner 'downing)
        (melissa-father 'barnacle)
        (mary-ann-yatch-owner (amb 'barnacle 'moore 'hall 'downing 'parker)))
            (require (not (eq? mary-ann-yatch-owner gabrielle-yatch-owner)))
            (require (not (eq? mary-ann-yatch-owner lorna-yatch-owner)))
            (require (not (eq? mary-ann-yatch-owner rosalind-yatch-owner)))
            (require (not (eq? mary-ann-yatch-owner melissa-yatch-owner)))
                (let ((gabrielle-father (amb 'barnacle 'moore 'hall 'downing 'parker))) 
                   (require (not (eq? melissa-father gabrielle-father))) 
                   (require (not (eq? gabrielle-yatch-owner gabrielle-father)))
                        (let ((rosalind-father (amb 'barnacle 'moore 'hall 'downing 'parker))) 
                            (require (not (eq? melissa-father rosalind-father))) 
                            (require (not (eq? gabrielle-father rosalind-father))) 
                            (require (not (eq? rosalind-yatch-owner rosalind-father))) 
                            )
                        (let ((lorna-father (amb 'barnacle 'moore 'hall 'downing 'parker)))
                            (require (not (= gabrielle-father lorna-father)))
                            (require (not (= melissa-father lorna-father)))
                            (require (not (= rosalind-father lorna-father)))
                                lorna-father))))

(display (yatch-owner-daughters-puzzle))
; 2 possibilites downing and parker