(define (square-tree tree) 
    (cond ((null? tree) '())
            ((not (pair? tree)) (square tree))
                (else (cons (square-tree (car tree)) 
                    (square-tree (cdr tree))))))

(define (square-tree-map tree) 
    (map (lambda (node) 
        (if (pair? node) (square-tree-map node)
            (square node))) 
            tree))