(define (corner-split painter n) 
    (if (= n 0)
        painter
        (let ((up (up-split painter (- n 1)))
            (right (right-split painter (- n 1))))
        (let ((corner (corner-split painter (- n 1))))
                (beside (below painter up)
                  (below right corner))))))

(define (square-of-four tl tr bl br) 
    (lambda (painter)
        (let ((top (beside (tl painter) (tr painter))) 
            (bottom (beside (bl painter) (br painter))))
                (below bottom top))))

 (define (square-limit painter n) 
   (let ((combine4 (square-of-four flip-vert rotate180 
                                   identity flip-horiz))) 
     (combine4 (corner-split painter n)))) 

(define wave 
   (segments->painter (list 
                       (make-segment (make-vect 0.25 0) (make-vect 0.35 0.5)) 
                       (make-segment (make-vect 0.35 0.5) (make-vect 0.3 0.6)) 
                       (make-segment (make-vect 0.3 0.6) (make-vect 0.15 0.4)) 
                       (make-segment (make-vect 0.15 0.4) (make-vect 0 0.65)) 
                       (make-segment (make-vect 0 0.65) (make-vect 0 0.85)) 
                       (make-segment (make-vect 0 0.85) (make-vect 0.15 0.6)) 
                       (make-segment (make-vect 0.15 0.6) (make-vect 0.3 0.65)) 
                       (make-segment (make-vect 0.3 0.65) (make-vect 0.4 0.65)) 
                       (make-segment (make-vect 0.4 0.65) (make-vect 0.35 0.85)) 
                       (make-segment (make-vect 0.35 0.85) (make-vect 0.4 1)) 
                       (make-segment (make-vect 0.4 1) (make-vect 0.6 1)) 
                       (make-segment (make-vect 0.6 1) (make-vect 0.65 0.85)) 
                       (make-segment (make-vect 0.65 0.85) (make-vect 0.6 0.65)) 
                       (make-segment (make-vect 0.6 0.65) (make-vect 0.75 0.65)) 
                       (make-segment (make-vect 0.75 0.65) (make-vect 1 0.35)) 
                       (make-segment (make-vect 1 0.35) (make-vect 1 0.15)) 
                       (make-segment (make-vect 1 0.15) (make-vect 0.6 0.45)) 
                       (make-segment (make-vect 0.6 0.45) (make-vect 0.75 0)) 
                       (make-segment (make-vect 0.75 0) (make-vect 0.6 0)) 
                       (make-segment (make-vect 0.6 0) (make-vect 0.5 0.3)) 
                       (make-segment (make-vect 0.5 0.3) (make-vect 0.4 0)) 
                       (make-segment (make-vect 0.4 0) (make-vect 0.25 0)) 
                       (make-segment (make-vect 0.44 0.7) (make-vect 0.51 0.7))
                       )))