(define (deep-reverse l)
  (define (recur count)
    (if (or (null? l) (< count 0))
        '()
            (cons (let ((item (list-ref l count)))
                (if (pair? item) (deep-reverse item) 
                    item))
                        (recur (- count 1)))))
                            (recur (- (length l) 1)))